services:
  - type: web
    name: arvayon-backend
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d7rm725ckfvc73a5gc50-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: arvayon_db
      - key: DB_USERNAME
        value: arvayon_db_user
      - key: DB_PASSWORD
        sync: false
      - key: APP_KEY
        sync: false
